#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authorController:
  path: /author
  controller: App\Controller\AuthorController::index

#bookController:
#  path: /books
#  controller: App\Controller\BookController::showBookLibrary